inherit_from:
  - .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'config/secrets.yml.enc'
    - 'config/unicorn.rb'
    - 'db/**/*'
    - 'log/*'
    - 'node_modules/**/*'
    - 'spec/features/tezos/bakers_spec.rb' # excluding this as this test will fail otherwise and break our CI
    - 'spec/features/mina/transactions_spec.rb'
    - 'spec/features/livepeer/dashboard_spec.rb'
    - 'spec/features/livepeer/delegator_lists_spec.rb'
    - 'vendor/bundle/ruby/**/*'

Layout/DotPosition:
  EnforcedStyle: trailing
Layout/EndAlignment:
  AutoCorrect: true
Layout/FirstArrayElementIndentation:
  Enabled: true
  EnforcedStyle: consistent
Layout/LineLength:
  AutoCorrect: true
  Max: 100
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented
Layout/SpaceAroundOperators:
  Enabled: true
  EnforcedStyleForExponentOperator: space

Lint/Debugger:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

Naming/FileName:
  Enabled: true
Naming/RescuedExceptionsVariableName:
  Enabled: false

Rails/ActiveRecordAliases:
  Enabled: true

Rails/LexicallyScopedActionFilter:
  Enabled: false

Rails/RakeEnvironment:
  Enabled: true

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
  - app/services/livepeer/queries/graph/*.rb
  - config/routes.rb
Style/ConditionalAssignment:
  Enabled: false
Style/Encoding:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/MethodCallWithArgsParentheses:
  # There is no "AllowedMethods" for this so will need more thinking
  Enabled: false
  Exclude:
  - Gemfile
  IgnoredMethods:
  - 'require'
  - 'gem'
  - 'require_relative'
  - 'use'
  - 'run'
Style/MultilineTernaryOperator:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Style/Semicolon:
  Enabled: true
  AllowAsExpressionSeparator: true
Style/SingleLineMethods:
  Enabled: true
Style/MissingRespondToMissing:
  Enabled: false
