shared:
  rollbar_token: YOUR_ROLLBAR_TOKEN
  recaptcha:
    site: RECAPTCHA_SITE
    secret: RECAPTCHA_SECRET
  database: {}

development:
  secret_key_base: DEV_SKB
  faucet_key_base: DEV_FKB
  telegram_api_key: DEV_TELEGRAM_KEY
  telegram_bot_name: DEV_TELEGRAM_BOT

staging:
  postmark:
    api_key: STAGING_POSTMARK
  secret_key_base: STAGING_SKB
  faucet_key_base: STAGING_FBK
  http_basic_password: PASSWORD
  database:
    name: hubble_staging
    password: STAGING_DB_PASS
    host: STAGING_DB_HOST
    user: STAGING_DB_USER
  telegram_api_key: STAGING_TELEGRAM_KEY
  telegram_bot_name: STAGING_TELEGRAM_BOT

production:
  postmark:
    api_key: PRODUCTION_POSTMARK
  secret_key_base: PRODUCTION_SKB
  faucet_key_base: PRODUCTION_FKB
  database:
    name: hubble
    password: PRODUCTION_DB_PASS
    host: PRODUCTION_DB_HOST
    user: PRODUCTION_DB_USER
  telegram_api_key: PRODUCTION_TELEGRAM_KEY
  telegram_bot_name: PRODUCTION_TELEGRAM_BOT
