shared:
  rollbar_token: YOUR_ROLLBAR_TOKEN
  recaptcha:
    site: RECAPTCHA_SITE
    secret: RECAPTCHA_SECRET

development:
  secret_key_base: DEV_SKB
  faucet_key_base: DEV_FKB

staging:
  postmark: STAGING_POSTMARK
  secret_key_base: STAGING_SKB
  faucet_key_base: STAGING_FBK
  http_basic_password: PASSWORD
  database:
    password: STAGING_DB_PASS
    host: STAGING_DB_HOST
    user: STAGING_DB_USER

production:
  postmark: PRODUCTION_POSTMARK
  secret_key_base: PRODUCTION_SKB
  faucet_key_base: PRODUCTION_FKB
  database:
    password: PRODUCTION_DB_PASS
    host: PRODUCTION_DB_HOST
    user: PRODUCTION_DB_USER
