shared:
  database: {}

development:
  application_host: localhost:3080
  application_protocol: http

staging:
  application_host: hubble-staging.figment.network
  application_protocol: https

production:
  application_host: hubble.figment.io
  application_protocol: https
