shared:
  database: {}

development:
  application_host: localhost:3080
  application_protocol: http

staging:
  application_host: hubble-staging.yourdomain.com
  application_protocol: https

production:
  application_host: hubble.yourdomain.com
  application_protocol: https
